Update README.md
jackpollinsK/team_4_Frontend pull request #18
Opened 2024-07-26 09:27 UTC by ThomasS-kainos

2024-07-26 10:20 UTC, jackpollinsK approved these changes

2024-07-26 10:44 UTC, shaunganley requested changes, later dismissed

2024-07-26 10:44 UTC, shaunganley commented on README.md
> +1. Follow the steps to run the backend for this application <a href="https://github.com/shaunganley/java-dropwizard-flyway-starter" target="_blank">here</a>
link to your teams API

2024-07-26 10:44 UTC, shaunganley commented on README.md
> +## How to run integration and unit tests locally
frontend doesn't have integration tests

2024-07-29 12:38 UTC, boydstepkainos approved these changes

2024-07-29 14:25 UTC, jackpollinsK approved these changes

2024-07-29 14:26 UTC, AdamB-Kainos approved these changes

2024-07-29 14:26 UTC, merged