View job roles UI test
jackpollinsK/team_4_Frontend pull request #34
Opened 2024-08-05 14:53 UTC by henrykainos

2024-08-06 13:01 UTC, shaunganley requested changes

2024-08-06 13:01 UTC, shaunganley commented on src/test/ui/ChromeDriver.ts
> +            //options.addArguments('headless'); // Ensure Chrome is running in headless mode
should this be uncommented?

2024-08-06 13:01 UTC, shaunganley commented on src/test/ui/ChromeDriver.ts
> +    async getElementByXpath(path: string) {
don't get anything by xpath, delete

2024-08-06 13:01 UTC, shaunganley commented on src/test/ui/ChromeDriver.ts
> +    async getTableById(id: string) {
this is a duplicate of getElementById method

2024-08-06 13:01 UTC, shaunganley commented on src/test/ui/ChromeDriver.ts
> +    async getTableWithXpath(xpath: string): Promise<WebElement> {
no xpath

2024-08-06 13:01 UTC, shaunganley commented on src/test/ui/JobRolesTestPage.ts
> +        const WEBSITE_URL = process.env.WEBSITE_URL;
have a default for local host if the url isn't set

2024-08-06 13:03 UTC, henrykainos commented on src/test/ui/ChromeDriver.ts
> +    async getElementByXpath(path: string) {
I use it as placeholder until ID's get implemented

2024-08-07 07:31 UTC, shaunganley approved these changes

2024-08-07 08:37 UTC, kajatraczykowska approved these changes

2024-08-07 08:37 UTC, merged