Delete job role
jackpollinsK/team_4_Frontend pull request #37
Opened 2024-08-06 14:56 UTC by AdamB-Kainos

2024-08-06 15:09 UTC, jackpollinsK commented on views/pages/allJobRolesList.html
add in id to assist in testing

2024-08-06 15:11 UTC, jackpollinsK requested changes

2024-08-06 15:11 UTC, jackpollinsK commented on views/pages/allJobRolesList.html
> +    <div class="container m-5">
add in id to help with testing

2024-08-06 15:30 UTC, jackpollinsK approved these changes

2024-08-07 07:30 UTC, shaunganley requested changes

2024-08-07 07:30 UTC, shaunganley commented on src/main/controllers/JobRoleController.ts
> +        res.render('pages/allJobRolesList.html', {jobRoles: await getJobRoles(req.session.token), pageName: "Job Roles", token: req.session.token, userLevel: jwtDecode(req.session.token)});
you could redirect here instead

2024-08-07 07:30 UTC, shaunganley commented on src/main/controllers/JobRoleController.ts
>          res.locals.pageName = "An Error Ocured";
pretty sure occurred is misspelt across this file

2024-08-07 07:30 UTC, shaunganley commented on src/test/unit/controller/JobRoleControllerTests.ts
> +        });
need another test for error being throw

2024-08-07 11:00 UTC, shaunganley approved these changes

2024-08-07 11:04 UTC, merged