Us012 add role
jackpollinsK/team_4_Frontend pull request #43
Opened 2024-08-07 15:15 UTC by jackpollinsK

2024-08-07 15:24 UTC, ThomasS-kainos requested changes

2024-08-07 15:24 UTC, ThomasS-kainos commented on views/snippets/nav.html
>      {href: '/jobRoles', id: 'Job Roles', caption: 'Jobs'},
Changed in main make sure to merge

2024-08-07 15:25 UTC, ThomasS-kainos commented on views/snippets/nav.html
>      {href: '/jobRoles', id: 'Job Roles', caption: 'Jobs'},
/AIJobSearch

2024-08-08 07:59 UTC, ThomasS-kainos submitted a review, later dismissed

2024-08-08 08:30 UTC, AdamB-Kainos submitted a review, later dismissed

2024-08-08 10:13 UTC, shaunganley requested changes
needs validator tests

2024-08-08 10:13 UTC, shaunganley commented on src/main/controllers/JobRoleController.ts
> +        ]);
love the use of promise.all here, nice job

2024-08-08 10:13 UTC, shaunganley commented on src/main/controllers/JobRoleController.ts
> +        const errors = validateJobRoleRequest(jobRoleRequest);
validation should happen in the service

2024-08-08 10:13 UTC, shaunganley commented on src/main/controllers/JobRoleController.ts
> +                selectedCapability: jobRoleRequest.capability,
can't you just pass back the whole request object?

2024-08-08 10:13 UTC, shaunganley commented on src/main/controllers/JobRoleController.ts
> +            res.redirect('/');
redirect to the job role details screen

2024-08-08 10:13 UTC, shaunganley commented on src/test/unit/controller/JobRoleControllerTests.ts
> +                sinon.stub(JobRoleService, 'createRole').resolves();
this should resolve an id which we can use to redirect to details page

2024-08-08 13:12 UTC, AdamB-Kainos approved these changes

2024-08-08 14:16 UTC, shaunganley approved these changes

2024-08-08 14:16 UTC, shaunganley commented on src/main/controllers/JobRoleController.ts
> +                : [e.message];
I don't think this actually does anything

2024-08-08 14:50 UTC, merged