make pa11y files run on AWS instead of localhost
jackpollinsK/team_4_Frontend pull request #49
Opened 2024-08-08 14:12 UTC by AdamB-Kainos

2024-08-08 14:18 UTC, shaunganley requested changes
pass in the baseUrl when running the test so we can run against AWS and localhost

2024-08-08 16:12 UTC, AdamB-Kainos commented
> pass in the baseUrl when running the test so we can run against AWS and localhost

fixed now

2024-08-09 07:05 UTC, shaunganley approved these changes

2024-08-09 07:13 UTC, PhilipGardinerK approved these changes

2024-08-09 07:15 UTC, merged